version: '3'

services:
  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: MySQL
    restart: always
    tty: true
    environment:
    - MYSQL_DATABASE=nodedb
    - MYSQL_ROOT_PASSWORD=mestre
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./mysql:/var/lib/mysql
    networks:
      - nodenet
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: renaninfra/nginx:prod
    container_name: nginx
    networks:
      - nodenet  
    ports:
      - "8080:80"
  nodejs: 
    build: 
      context: ./projeto
      dockerfile: Dockerfile
    image: renaninfra/nodejs:prod
    container_name: nodejs
    restart: always
    tty: true
    networks:
      - nodenet  
    depends_on:
      - db
    command: sh -c "sleep 10 && node index.js"  
networks:
  nodenet:
    driver: bridge
      

